extends RefCounted
class_name ArmorGreebles
# Makes the four hull ARMOR MATERIALS visually distinguishable by GEOMETRY
# rather than only by shader tint.
#
# THE PROBLEM
# ---------------------------------------------------------------------------
# hull_material_builder.gd already parameterises colour, wear, grime, metallic
# and roughness per material - and that is exactly why the four read as one
# material in four paint schemes at gameplay distance. A roughness value does
# not survive being 40 pixels tall; a field of rivets does. Real armour types
# are distinguished by repetition at silhouette scale: riveted plate, bricks
# of ERA, a mosaic of ceramic tiles.
#
# THE SHAPE OF THIS FILE
# ---------------------------------------------------------------------------
# This is deliberately thin. All the placement work lives in
# greeble_field.gd, which is a general data-driven engine, so everything here
# is a SPEC TABLE plus the one special case (the shield bubble) that is not a
# scatter at all. Adding a fifth armour material means adding a row to
# MATERIAL_GREEBLES and authoring one mesh - no new placement code.

const GreebleFieldScript = preload("res://scripts/greeble_field.gd")
const HullProjectionScript = preload("res://scripts/hull_projection.gd")

const CONTAINER_NAME := "ArmorGreebles"
const SHIELD_NAME := "EnergyShield"
const SHIELD_SHADER = preload("res://shaders/energy_shield.gdshader")

# One row per armour material. `faces` is chosen per material for a reason,
# not for variety: rivets belong everywhere because plate is welded
# everywhere; ERA belongs on the faces that get shot at, because nobody
# straps explosive bricks to the underside; ceramic tiles are a full mosaic.
const MATERIAL_GREEBLES := {
	"hardened_steel": [{
		"part": "armor_stud_bolt",
		"spacing": 0.62,
		"faces": ["top", "left", "right", "front", "back"],
		"tint": Color(0.36, 0.37, 0.39),
		"metallic": 0.80, "roughness": 0.42,
		"jitter": 0.10, "scale": 1.0, "yaw_random": false,
		"max_instances": 150,
	}],
	"reactive_armor": [{
		# Bigger and sparser than rivets: ERA bricks are individually large,
		# and a hull plastered edge-to-edge in them would read as texture
		# rather than as discrete replaceable blocks.
		"part": "armor_reactive_block",
		"spacing": 0.78,
		"faces": ["top", "left", "right", "front"],
		"tint": Color(0.30, 0.33, 0.27),
		"metallic": 0.35, "roughness": 0.62,
		"jitter": 0.05, "scale": 1.0, "yaw_random": false,
		"max_instances": 90,
	}],
	"ablative_ceramic": [{
		# Tight and regular - a mosaic only reads as a mosaic if the tiles
		# nearly touch, so this has the smallest spacing and lowest jitter.
		"part": "armor_ceramic_tile",
		"spacing": 0.40,
		"faces": ["top", "left", "right", "front", "back"],
		"tint": Color(0.68, 0.66, 0.60),
		"metallic": 0.02, "roughness": 0.52,
		"jitter": 0.02, "scale": 1.0, "yaw_random": false,
		"max_instances": 200,
	}],
	# energy_shielding has NO scatter row on purpose - see apply() below. A
	# shield is generated by a few emitters, not by cladding, so covering the
	# hull in projectors would say the opposite of what the material does.
	"energy_shielding": [],
}

const EMITTER_SPEC := {
	"part": "armor_shield_emitter",
	"tint": Color(0.30, 0.34, 0.40),
	"metallic": 0.70, "roughness": 0.30,
	"scale": 1.0, "inset": 0.82,
}

# The bubble has to CONTAIN the hull, and the containment factor is not a
# taste call - it is geometry. An ellipsoid whose semi-axes match a box's
# half-extents passes through the box's FACE centres but cuts its CORNERS
# off; to enclose the corners the axes must grow by sqrt(3), because a corner
# sits at (1,1,1) in normalised axis space and 1/1+1/1+1/1 = 3.
#
# The first pass used 1.22, which looked like a reasonable margin and left
# every corner of the hull poking through the shield - a mistake that reads
# as clipping rather than as a design choice. 1.75 is sqrt(3) plus a little
# clearance so the skin does not graze the corners either.
const SHIELD_MARGIN := 1.75
const SHIELD_MIN_RADIUS := 1.1

static func apply(hull: Node3D, _material: String = "", _hull_size: Vector3 = Vector3.ONE) -> void:
	if not is_instance_valid(hull):
		return
	var old = hull.get_node_or_null(CONTAINER_NAME)
	if old:
		old.queue_free()

# The visible shield: a mostly-transparent ellipsoid with crackling arcs that
# travel across it (energy_shield.gdshader). Not collidable and not on any
# physics layer - it is purely a read, and the actual mitigation is
# damage_resolver's business.
static func _build_shield_bubble(container: Node3D, hull_size: Vector3) -> void:
	var bubble = MeshInstance3D.new()
	bubble.name = SHIELD_NAME
	var sphere = SphereMesh.new()
	sphere.radius = 1.0
	sphere.height = 2.0
	sphere.radial_segments = 32
	sphere.rings = 16
	bubble.mesh = sphere
	# Y gets extra headroom on top of the sqrt(3): hulls are wide and long but
	# shallow, and an ellipsoid that only just clears a 1.4-tall hull looks
	# squashed onto it. Everything mounted on the roof also has to fit inside.
	bubble.scale = Vector3(
		maxf(SHIELD_MIN_RADIUS, hull_size.x * 0.5 * SHIELD_MARGIN),
		maxf(SHIELD_MIN_RADIUS * 1.3, hull_size.y * 0.5 * SHIELD_MARGIN * 1.9),
		maxf(SHIELD_MIN_RADIUS, hull_size.z * 0.5 * SHIELD_MARGIN))
	bubble.position = Vector3(0, hull_size.y * 0.30, 0)

	var mat = ShaderMaterial.new()
	mat.shader = SHIELD_SHADER
	mat.set_shader_parameter("shield_color", Color(0.35, 0.72, 1.0))
	bubble.material_override = mat

	# Never occlude or receive shadows - it is an additive overlay, and a
	# shadow-casting bubble would darken the vehicle it is protecting.
	bubble.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	container.add_child(bubble)
