
func update_stats(hull: Node3D): telemetry_rail.update_stats(hull)
func _push_undo(): lab_toolbar._push_undo()
func _on_delete_pressed(): lab_toolbar._on_delete_pressed()
func _on_save_pressed(): lab_toolbar._on_save_pressed()
func _on_test_pressed(): lab_toolbar._on_test_pressed()
func _on_mirror_toggled(button_pressed: bool): lab_toolbar._on_mirror_toggled(button_pressed)
func _on_library_pressed(): lab_toolbar._on_library_pressed()
func _on_blueprint_name_changed(new_text: String): lab_toolbar._on_blueprint_name_changed(new_text)
func _on_roll_name_pressed(): lab_toolbar._on_roll_name_pressed()

func on_module_selected(module: Node3D): tweak_callout_manager.on_module_selected(module)
func _on_size_value_changed(value: float): tweak_callout_manager._on_size_value_changed(value)
func _on_count_value_changed(value: float): tweak_callout_manager._on_count_value_changed(value)
func _on_wheels_per_axle_changed(value: float): tweak_callout_manager._on_wheels_per_axle_changed(value)
func _on_blade_count_changed(value: float): tweak_callout_manager._on_blade_count_changed(value)
func _on_blade_pitch_changed(value: float): tweak_callout_manager._on_blade_pitch_changed(value)
func _on_helix_depth_changed(value: float): tweak_callout_manager._on_helix_depth_changed(value)
func _on_leg_width_changed(value: float): tweak_callout_manager._on_leg_width_changed(value)
func _on_duct_toggled(pressed: bool): tweak_callout_manager._on_duct_toggled(pressed)
func _on_leg_type_selected(index: int): tweak_callout_manager._on_leg_type_selected(index)
func _on_loco_drag_started(): tweak_callout_manager._on_loco_drag_started()
func _on_loco_drag_ended(value_changed: bool): tweak_callout_manager._on_loco_drag_ended(value_changed)
